name: CI/CD

on:
  push:
    branches: [ '*' ]
  pull_request:
      branches: [ '*' ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: echo "${{ secrets.TEST_ENV }}" > ../backend/.env
      - name: Install dependencies
        run: npm ci
      - name: Check linting
        run: npm run lint
      - name: Build app
        run: npm run build

  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.TEST_ENV }}" > .env

      - name: Build and start Docker containers
        run: docker compose up --build -d mysql backend

      - name: Run tests
        run: docker compose exec backend pytest

  deploy:
    needs: [ test-frontend, test-backend ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          echo '${{ secrets.PROD_FRONT_ENV }}' > .env
          npm install
          npm run build

      - run: tar -czf frontend-build.tar.gz -C frontend/dist .

      - name: Transfer Build to Server
        run: scp frontend-build.tar.gz root@${{ secrets.SERVER_IP }}:/tmp/frontend-build.tar.gz

      - name: Deploy to server
        run: ssh root@${{ secrets.SERVER_IP }} "
          cd ~/PigCoin &&
          git pull &&
          echo '${{ secrets.PROD_BACK_ENV }}' > ./backend/.env &&
          tar -xzf /tmp/frontend-build.tar.gz -C /var/www/pigcoin.evicon.fun/html/ &&
          docker compose up --build -d
          "
